import { Product, BlogPost } from '@/app/types';

export const products: Product[] = [
  // CHAIRS
  {
    id: '1',
    name: 'Modern Upholstered Armchair',
    price: 349.00,
    image: '/products/Chairs/IMAGE 2026-06-14 17:08:08.jpg',
    category: 'Chairs',
    material: 'Fabric',
    color: 'Grey',
    rating: 4.8,
    reviews: 245,
    inStock: true,
    description: 'Contemporary armchair with comfortable upholstering and sleek design.'
  },
  {
    id: '2',
    name: 'Classic Wooden Chair',
    price: 199.00,
    image: '/products/Chairs/IMAGE 2026-06-14 17:08:10.jpg',
    category: 'Chairs',
    material: 'Wood',
    color: 'Natural Oak',
    rating: 4.6,
    reviews: 189,
    inStock: true,
    description: 'Timeless wooden chair perfect for dining or workspace.'
  },
  {
    id: '3',
    name: 'Luxury Lounge Chair',
    price: 599.00,
    originalPrice: 799.00,
    image: '/products/Chairs/IMAGE 2026-06-14 17:08:13.jpg',
    category: 'Chairs',
    material: 'Premium Fabric',
    color: 'Cream',
    rating: 4.9,
    reviews: 312,
    inStock: true,
    description: 'Premium lounging experience with luxurious comfort.'
  },
  {
    id: '4',
    name: 'Dining Accent Chair',
    price: 249.00,
    image: '/products/Chairs/IMAGE 2026-06-14 17:08:15.jpg',
    category: 'Chairs',
    material: 'Fabric',
    color: 'Charcoal',
    rating: 4.5,
    reviews: 124,
    inStock: true,
  },
  {
    id: '5',
    name: 'Ergonomic Office Chair',
    price: 399.00,
    image: '/products/Chairs/IMAGE 2026-06-14 17:08:18.jpg',
    category: 'Chairs',
    material: 'Mesh',
    color: 'Black',
    rating: 4.7,
    reviews: 156,
    inStock: true,
  },
  // SOFAS
  {
    id: '6',
    name: 'Modern 3-Seater Sofa',
    price: 899.00,
    originalPrice: 1199.00,
    image: '/products/Sofas/IMAGE 2026-06-14 17:19:51.jpg',
    category: 'Sofas',
    material: 'Fabric',
    color: 'Grey',
    rating: 4.8,
    reviews: 298,
    inStock: true,
    description: 'Spacious sofa perfect for family gatherings and relaxation.'
  },
  {
    id: '7',
    name: 'Minimalist Linen Sofa',
    price: 749.00,
    image: '/products/Sofas/IMAGE 2026-06-14 17:19:53.jpg',
    category: 'Sofas',
    material: 'Linen',
    color: 'Beige',
    rating: 4.7,
    reviews: 201,
    inStock: true,
  },
  {
    id: '8',
    name: 'Luxury Leather Sofa',
    price: 1299.00,
    image: '/products/Sofas/IMAGE 2026-06-14 17:19:55.jpg',
    category: 'Sofas',
    material: 'Leather',
    color: 'Cognac',
    rating: 4.9,
    reviews: 145,
    inStock: true,
  },
  {
    id: '9',
    name: 'Compact L-Shaped Sofa',
    price: 799.00,
    image: '/products/Sofas/IMAGE 2026-06-14 17:19:57.jpg',
    category: 'Sofas',
    material: 'Fabric',
    color: 'Navy',
    rating: 4.6,
    reviews: 178,
    inStock: true,
  },
  // TABLES
  {
    id: '10',
    name: 'Walnut Coffee Table',
    price: 299.00,
    image: '/products/Tables/IMAGE 2026-06-14 17:20:14.jpg',
    category: 'Tables',
    material: 'Wood',
    color: 'Walnut',
    rating: 4.7,
    reviews: 215,
    inStock: true,
    description: 'Elegant coffee table with solid wood construction.'
  },
  {
    id: '11',
    name: 'Glass Dining Table',
    price: 599.00,
    image: '/products/Tables/IMAGE 2026-06-14 17:20:17.jpg',
    category: 'Tables',
    material: 'Glass',
    color: 'Clear',
    rating: 4.5,
    reviews: 142,
    inStock: true,
  },
  {
    id: '12',
    name: 'Marble Side Table',
    price: 349.00,
    image: '/products/Tables/IMAGE 2026-06-14 17:20:19.jpg',
    category: 'Tables',
    material: 'Marble',
    color: 'White',
    rating: 4.8,
    reviews: 189,
    inStock: true,
  },
  {
    id: '13',
    name: 'Industrial Steel Table',
    price: 449.00,
    image: '/products/Tables/IMAGE 2026-06-14 17:20:29.jpg',
    category: 'Tables',
    material: 'Steel',
    color: 'Black',
    rating: 4.6,
    reviews: 156,
    inStock: true,
  },
  // BEDS
  {
    id: '14',
    name: 'Modern Platform Bed',
    price: 799.00,
    image: '/products/Beds/IMAGE 2026-06-14 17:21:05.jpg',
    category: 'Beds',
    material: 'Wood',
    color: 'Natural',
    rating: 4.7,
    reviews: 234,
    inStock: true,
    description: 'Minimalist platform bed with integrated storage options.'
  },
  {
    id: '15',
    name: 'Luxury Upholstered Bed',
    price: 1099.00,
    image: '/products/Beds/IMAGE 2026-06-14 17:21:07.jpg',
    category: 'Beds',
    material: 'Fabric',
    color: 'Grey',
    rating: 4.9,
    reviews: 201,
    inStock: true,
  },
  {
    id: '16',
    name: 'Classic Metal Bed Frame',
    price: 499.00,
    image: '/products/Beds/IMAGE 2026-06-14 17:21:09.jpg',
    category: 'Beds',
    material: 'Metal',
    color: 'Black',
    rating: 4.5,
    reviews: 123,
    inStock: true,
  },
  // SHELVES & STORAGE
  {
    id: '17',
    name: 'Wall-Mounted Floating Shelf',
    price: 129.00,
    image: '/products/Shelves/IMAGE 2026-06-14 17:20:49.jpg',
    category: 'Storage',
    material: 'Wood',
    color: 'Natural',
    rating: 4.6,
    reviews: 178,
    inStock: true,
  },
  {
    id: '18',
    name: 'Modular Storage Unit',
    price: 449.00,
    image: '/products/Shelves/IMAGE 2026-06-14 17:20:50.jpg',
    category: 'Storage',
    material: 'Wood',
    color: 'White',
    rating: 4.7,
    reviews: 212,
    inStock: true,
  },
  {
    id: '19',
    name: 'Tall Bookshelf Cabinet',
    price: 399.00,
    image: '/products/Shelves/IMAGE 2026-06-14 17:20:53.jpg',
    category: 'Storage',
    material: 'Wood',
    color: 'Oak',
    rating: 4.5,
    reviews: 145,
    inStock: true,
  },
  {
    id: '20',
    name: 'Industrial Metal Shelving',
    price: 349.00,
    image: '/products/Shelves/IMAGE 2026-06-14 17:20:55.jpg',
    category: 'Storage',
    material: 'Steel',
    color: 'Black',
    rating: 4.6,
    reviews: 189,
    inStock: true,
  },
  // DESKS & OFFICE
  {
    id: '21',
    name: 'Executive Workspace Desk',
    price: 699.00,
    image: '/products/Desk & Office/IMAGE 2026-06-14 17:21:27.jpg',
    category: 'Desks',
    material: 'Wood',
    color: 'Walnut',
    rating: 4.8,
    reviews: 198,
    inStock: true,
  },
  {
    id: '22',
    name: 'Minimalist Home Office Desk',
    price: 449.00,
    image: '/products/Desk & Office/IMAGE 2026-06-14 17:21:30.jpg',
    category: 'Desks',
    material: 'Wood',
    color: 'White',
    rating: 4.6,
    reviews: 167,
    inStock: true,
  },
  {
    id: '23',
    name: 'Adjustable Standing Desk',
    price: 599.00,
    image: '/products/Desk & Office/IMAGE 2026-06-14 17:21:33.jpg',
    category: 'Desks',
    material: 'Wood/Metal',
    color: 'Natural',
    rating: 4.7,
    reviews: 234,
    inStock: true,
  },
  // LIGHTING
  {
    id: '24',
    name: 'Modern Floor Lamp',
    price: 229.00,
    image: '/products/Lamp & Lighting/IMAGE 2026-06-14 17:21:45.jpg',
    category: 'Lighting',
    material: 'Metal',
    color: 'Black',
    rating: 4.7,
    reviews: 156,
    inStock: true,
  },
  {
    id: '25',
    name: 'Pendant Hanging Light',
    price: 189.00,
    image: '/products/Lamp & Lighting/IMAGE 2026-06-14 17:21:48.jpg',
    category: 'Lighting',
    material: 'Glass',
    color: 'Amber',
    rating: 4.5,
    reviews: 112,
    inStock: true,
  },
  {
    id: '26',
    name: 'Table Desk Lamp',
    price: 99.00,
    image: '/products/Lamp & Lighting/IMAGE 2026-06-14 17:21:50.jpg',
    category: 'Lighting',
    material: 'Metal',
    color: 'Silver',
    rating: 4.6,
    reviews: 134,
    inStock: true,
  },
  // RUGS & ACCESSORIES
  {
    id: '27',
    name: 'Premium Area Rug',
    price: 399.00,
    image: '/products/Rugs & Accessories/IMAGE 2026-06-14 17:22:00.jpg',
    category: 'Rugs',
    material: 'Wool',
    color: 'Grey',
    rating: 4.8,
    reviews: 201,
    inStock: true,
  },
  {
    id: '28',
    name: 'Decorative Throw Pillow Set',
    price: 149.00,
    image: '/products/Rugs & Accessories/IMAGE 2026-06-14 17:22:07.jpg',
    category: 'Accessories',
    material: 'Fabric',
    color: 'Mixed',
    rating: 4.6,
    reviews: 178,
    inStock: true,
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: '10 Tips for a Minimalist Living Room',
    excerpt: 'Transform your space with these simple minimalist design principles...',
    image: '/products/Hero:Banner images/IMAGE 2026-06-14 17:22:28.jpg',
    date: 'Mar 15, 2024',
    category: 'Design Tips'
  },
  {
    id: '2',
    title: 'How to Choose the Perfect Sofa',
    excerpt: 'Everything you need to know about selecting the right sofa for your home...',
    image: '/products/Hero:Banner images/IMAGE 2026-06-14 17:22:30.jpg',
    date: 'Mar 10, 2024',
    category: 'Furniture Guide'
  },
  {
    id: '3',
    title: 'Color Trends for Your Home in 2024',
    excerpt: 'Discover the hottest color palettes trending this year...',
    image: '/products/Hero:Banner images/IMAGE 2026-06-14 17:22:33.jpg',
    date: 'Mar 5, 2024',
    category: 'Trends'
  },
];
